export interface ProjectsData {
  id: number;
  title: string;
  description: string;
  image: string;
  owner: string;
  enterprise: string;
  datetitle: string;
  date: string;
  url: string;
}

const projectsData: ProjectsData[] = [
    {
    id: 1,
    title: "GREEN CARD",
    description: "Création d'un site web dédié à la conception de cartes de visite personnalisées en impression 3D",
    image: "/projects/green_card.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Mai 2025",
    url: "#",
    },
    {
    id: 2,
    title: "SERIGRAFIK SOLUTIONS",
    description: "Création d’un site e-commerce dédié à la personnalisation de textiles via la sérigraphie. L’utilisateur peut choisir un produit (t-shirt, sweat, tote bag…), ajouter ses visuels ou textes, et prévisualiser le rendu final en temps réel avant de commander. Le site propose une expérience fluide et intuitive, adaptée aux besoins d’associations, d’entreprises ou de particuliers.",
    image: "/projects/ss.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Mars 2025",
    url: "#",
    },
    {
    id: 3,
    title: "ARCHITECTURE STUDIO",
    description: "Nous avons développé une application de type chatbot, connectée au modèle de langage MistralAI, permettant une interaction fluide et intelligente avec les utilisateurs. Cette solution est conçue pour faciliter la gestion de projets complexes en offrant une organisation thématique, idéale pour des environnements variés tels que les hôpitaux, les écoles ou autres institutions. Chaque projet est rattaché à une thématique, qui regroupe plusieurs domaines d’expertise (par exemple : Agent IA Expert). L’utilisateur peut téléverser ses données, qui sont automatiquement segmentées et vectorisées grâce à Qdrant, une technologie de base vectorielle performante. Le système permet ensuite de poser des questions précises à l’IA, qui s’appuie sur les données du projet pour fournir des réponses ciblées et pertinentes. C’est un outil précieux pour les architectes ou les équipes projet, qui peuvent ainsi accéder rapidement à une base de connaissances contextuelle et intelligente.",
    image: "/projects/architecturestudio.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Mars 2025",
    url: "#",
    },
    {
    id: 4,
    title: "CPTS",
    description: "Site web de la CPTS conçu pour centraliser les infos utiles pour les patients, les pros de santé (adhérents ou non) et les étudiants : annuaire, actualités, projets, offres d’emploi, annonces de remplacement, espace sécurisé pour les adhérents, et valorisation du dynamisme du territoire.",
    image: "/projects/cpts.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Mars 2025",
    url: "#",
    },
    {
    id: 5,
    title: "EA",
    description: "Création d’une application web dans le domaine du e-commerce. Les utilisateurs peuvent choisir une gamme de produits et les personnaliser.",
    image: "/projects/ea.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Janvier 2025",
    url: "#",
    },
    {
    id: 6,
    title: "GOTSTAF",
    description: "Création d’un site vitrine pour un grand artiste, permettant de mettre en avant ses œuvres et de les vendre.",
    image: "/projects/gotstaf.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Juillet 2024",
    url: "#",
    },
    {
    id: 7,
    title: "MILENA REFLEXOLOGIE",
    description: "Création d’un site web pour une réflexologue, permettant de mettre en avant ses services et de faciliter la prise de rendez-vous.",
    image: "/projects/milena_logo.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Avril 2024",
    url: "#",
    },
    {
    id: 8,
    title: "ART OF NANA",
    description: "Création d’un portfolio pour une grande artiste, permettant de mettre en avant ses œuvres et de les vendre.",
    image: "/projects/art_of_nana.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Mars 2024",
    url: "#",
    },
    {
    id: 9,
    title: "LA CIME DES APPS",
    description: "Élaboration de ce site web. Et oui, les cordonniers ne sont pas toujours les plus mal chaussés.",
    image: "/projects/lacimedesapps.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Janvier 2024",
    url: "#",
    },
    {
    id: 10,
    title: "ASISPO",
    description: "Création d’une application web utilisant plusieurs technologies et de l’intelligence artificielle pour améliorer le suivi post-opératoire.",
    image: "/projects/asispo.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Mars 2022",
    url: "#",
    },
    {
    id: 11,
    title: "MONTHABOR",
    description: "Création d’une application web dans le domaine de l’immobilier, favorisant la mise en relation entre les agences et les clients potentiels.",
    image: "/projects/mont_thabor.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Novembre 2021",
    url: "#",
    },
    {
    id: 12,
    title: "RESTORE RESET",
    description: "Création d’une application web dans le domaine de la restauration, favorisant la mise en relation entre les restaurateurs et les employés potentiels.",
    image: "/projects/restore_reset.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Février 2021",
    url: "#",
    },
    {
    id: 13,
    title: "YMED",
    description: "Création d’une application CMS pour les hôpitaux, permettant d’administrer et de créer leurs sites web.",
    image: "/projects/ymed.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Mars 2020",
    url: "#",
    },    
    {
    id: 14,
    title: "GRAVITR",
    description: "Création d’une application web dans le domaine du marketing afin de faciliter la mise en relation entre spécialistes et industries.",
    image: "/projects/gravitr.png",
    owner: "By Jonas",
    enterprise: "La Cime Des Apps",
    datetitle: "Date de réalisation",
    date: "Décembre 2019",
    url: "#",
    }
];

export default projectsData;